// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TextTranslator.Models
{
    public partial class TextTranslatorDBContext : DbContext
    {
        public TextTranslatorDBContext()
        {
        }

        public TextTranslatorDBContext(DbContextOptions<TextTranslatorDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<Translator> Translators { get; set; }
        public virtual DbSet<TopTranslator> TopTranslator { get; set; }

        public IList<TopTranslator> ExecuteGetMostUsedTranslator()
        {
            var result = this.Set<TopTranslator>().FromSqlInterpolated($"EXEC GetMostUsedTranslator").ToList();
            return result;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Translation>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.DateCreated)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Result).HasMaxLength(500);

                entity.Property(e => e.Text).HasMaxLength(500);

                entity.HasOne(d => d.Translator)
                    .WithMany(p => p.Translations)
                    .HasForeignKey(d => d.TranslatorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Translations_Translators");
            });

            modelBuilder.Entity<Translator>(entity =>
            {
                entity.Property(e => e.DateCreated)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DateModified)
                    .HasColumnType("date")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Name)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Url)
                    .HasMaxLength(500)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}