// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TextTranslator.Models
{
    public partial class Translation
    {
        public Guid Id { get; set; }
        public string Text { get; set; }
        public string Result { get; set; }
        public int TranslatorId { get; set; }
        public DateTime? DateCreated { get; set; }

        public virtual Translator Translator { get; set; }
    }
}